version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
  web:
    build: .
    volumes:
      - .:/cncnet-map-api
      - ${MEDIA_ROOT}:/data/cncnet_files
      - ${STATIC_ROOT}:/data/cncnet_static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  test:
    build:
      context: ./
      dockerfile: test.DockerFile
    volumes:
      - .:/cncnet-map-api
    env_file:
      - .env
    environment:
      POSTGRES_TEST_HOST: db  # Necessary to connect to docker db. Overrides the .env setting.
    depends_on:
      - db
    command:
      - pytest
