services:
  db:
    image: postgres
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${STATIC_ROOT}:/usr/share/nginx/html/static
      - ${MEDIA_ROOT}:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    volumes:
      - .:/cncnet-map-api
      - ${MEDIA_ROOT}:/data/cncnet_files
      - ${STATIC_ROOT}:/data/cncnet_static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: [ "gunicorn", "kirovy.wsgi:application", "--bind", "0.0.0.0:8000" ]


  test:
    build:
      context: ./
      dockerfile: test.DockerFile
    volumes:
      - .:/cncnet-map-api
    env_file:
      - .env
    environment:
      POSTGRES_TEST_HOST: db  # Necessary to connect to docker db. Overrides the .env setting.
    depends_on:
      - db
    command:
      - pytest

  windows-dev:
    # Use this for windows. The LZO libraries are annoying to deal with without using docker.
    # Chairman Bing of Massivesoft strikes again.
    build:
      context: ./
      dockerfile: test.DockerFile
    volumes:
      - .:/cncnet-map-api
    env_file:
      - .env
    environment:
      POSTGRES_TEST_HOST: db  # Necessary to connect to docker db. Overrides the .env setting.
    depends_on:
      - db
