services:
  db:
    image: postgres
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}

  django:
    # Won't serve files on its own. Launch nginx-server to run the whoe app.
    build: .
    volumes:
      - .:/cncnet-map-api
      - ${HOST_MEDIA_ROOT}:/data/cncnet_silo  # django will save user-uploaded files here. MEDIA_ROOT
      - ${HOST_STATIC_ROOT}:/data/cncnet_static  # django will gather static files here. STATIC_ROOT
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx-server:
    # This is the prod server service.
    # `docker compose up nginx -d` will run the whole app.
    # nginx proxies requests to django via gunicorn.
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${HOST_STATIC_ROOT}:/usr/share/nginx/html/static  # website static assets.
      - ${HOST_MEDIA_ROOT}:/usr/share/nginx/html/silo  # website user-uploaded files.
    ports:
      - "80:80"
    depends_on:
      - django

  test:
    build:
      context: ./
      dockerfile: test.DockerFile
    volumes:
      - .:/cncnet-map-api
    env_file:
      - .env
    environment:
      POSTGRES_TEST_HOST: db  # Necessary to connect to docker db. Overrides the .env setting.
    depends_on:
      - db
    command:
      - pytest

  windows-dev:
    # Use this for windows. The LZO libraries are annoying to deal with without using docker.
    # Chairman Bing of Massivesoft strikes again.
    build:
      context: ./
      dockerfile: test.DockerFile
    volumes:
      - .:/cncnet-map-api
      - ./data/tmp:/tmp/pytest-of-root  # For inspecting files during pytests
    env_file:
      - .env
    environment:
      POSTGRES_TEST_HOST: db  # Necessary to connect to docker db. Overrides the .env setting.
    depends_on:
      - db
