# Generated by Django 4.2.5 on 2024-01-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kirovy.models.cnc_game
import kirovy.models.file_base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CncUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cncnet_id",
                    models.IntegerField(
                        editable=False,
                        help_text="The user ID from the CNCNet ladder API.",
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="The name from the CNCNet ladder API.", null=True
                    ),
                ),
                ("verified_map_uploader", models.BooleanField(default=False)),
                ("verified_email", models.BooleanField(default=False)),
                (
                    "group",
                    models.CharField(
                        help_text="The user group from the CNCNet ladder API."
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="If true, user was banned for some reason.",
                    ),
                ),
                (
                    "ban_reason",
                    models.CharField(
                        default=None,
                        help_text="If banned, the reason the user was banned.",
                        null=True,
                    ),
                ),
                (
                    "ban_date",
                    models.DateTimeField(
                        default=None,
                        help_text="If banned, when the user was banned.",
                        null=True,
                    ),
                ),
                (
                    "ban_expires",
                    models.DateTimeField(
                        default=None,
                        help_text="If banned, when the ban expires, if temporary.",
                        null=True,
                    ),
                ),
                (
                    "ban_count",
                    models.IntegerField(
                        default=0, help_text="How many times this user has been banned."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CncFileExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "extension",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[kirovy.models.cnc_game.is_valid_extension],
                    ),
                ),
                ("about", models.CharField(max_length=2048, null=True)),
                (
                    "extension_type",
                    models.CharField(
                        choices=[("map", "map"), ("assets", "assets")], max_length=32
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CncGame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.CharField(max_length=16, unique=True)),
                ("full_name", models.CharField(max_length=128)),
                ("is_visible", models.BooleanField(default=False)),
                ("allow_public_uploads", models.BooleanField(default=False)),
                ("compatible_with_parent_maps", models.BooleanField(default=False)),
                ("is_mod", models.BooleanField(default=False)),
                (
                    "allowed_extensions",
                    models.ManyToManyField(to="kirovy.cncfileextension"),
                ),
                (
                    "parent_game",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kirovy.cncgame",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CncMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("map_name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=4096)),
                (
                    "is_legacy",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this is an upload from the old cncnet database.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this map will show up in normal searches and feeds.",
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this will be deleted eventually. This flag is to support sharing in multiplayer lobbies.",
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this map was reviewed by a staff member.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MapCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CncMapFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=kirovy.models.file_base._generate_upload_to
                    ),
                ),
                ("hash_md5", models.CharField(max_length=32)),
                ("hash_sha512", models.CharField(max_length=512)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("version", models.IntegerField()),
                (
                    "cnc_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="kirovy.cncgame"
                    ),
                ),
                (
                    "cnc_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kirovy.cncmap"
                    ),
                ),
                (
                    "file_extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kirovy.cncfileextension",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cncmap",
            name="categories",
            field=models.ManyToManyField(to="kirovy.mapcategory"),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="cnc_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kirovy.cncgame"
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="cnc_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="cncmapfile",
            constraint=models.UniqueConstraint(
                fields=("cnc_map_id", "version"), name="unique_map_version"
            ),
        ),
        migrations.AlterModelManagers(
            name="cncuser",
            managers=[
                ("objects", kirovy.models.cnc_user.CncUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="cncfileextension",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncgame",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="If true, this map will be hidden everywhere. Likely due to breaking a rule.",
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="legacy_upload_date",
            field=models.DateTimeField(
                default=None,
                help_text="The original upload date for entries imported from the legacy map database.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cncmapfile",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mapcategory",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
