# Generated by Django 4.2.5 on 2023-11-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0002_add_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmapfile",
            name="version",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cncmapfile",
            name="cnc_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kirovy.cncmap"
            ),
        ),
        migrations.AddConstraint(
            model_name="cncmapfile",
            constraint=models.UniqueConstraint(
                fields=("cnc_map_id", "version"), name="unique_map_version"
            ),
        ),
    ]
