# Generated by Django 4.2.5 on 2024-01-19 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0002_add_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncfileextension",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncgame",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="If true, this map will be hidden everywhere. Likely due to breaking a rule.",
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="legacy_upload_date",
            field=models.DateTimeField(
                default=None,
                help_text="The original upload date for entries imported from the legacy map database.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cncmapfile",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mapcategory",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
