# Generated by Django 4.2.5 on 2024-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0003_map_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmap",
            name="incomplete_upload",
            field=models.BooleanField(
                default=False,
                help_text="If true, then the map file has been uploaded, but the map info has not been set yet.",
            ),
        ),
    ]
