# Generated by Django 4.2.11 on 2024-05-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0005_alter_cncmapfile_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmap",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kirovy.cncmap",
            ),
        ),
    ]
