# Generated by Django 4.2.20 on 2025-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0009_mappreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmapfile",
            name="hash_sha1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mappreview",
            name="hash_sha1",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
