# Generated by Django 4.2.20 on 2025-03-23 23:32

from django.db import migrations, models
import kirovy.models.file_base


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0012_raw_zip_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmap",
            name="is_mapdb1_compatible",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cncmapfile",
            name="file",
            field=models.FileField(upload_to=kirovy.models.file_base._generate_upload_to),
        ),
    ]
