# Generated by Django 4.2.23 on 2025-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0014_cncmapimagefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cncmapimagefile",
            name="version",
        ),
        migrations.AddField(
            model_name="cncmapimagefile",
            name="image_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cncmapimagefile",
            name="is_extracted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="cncfileextension",
            index=models.Index(fields=["extension_type"], name="kirovy_cncf_extensi_5e0362_idx"),
        ),
        migrations.AddIndex(
            model_name="cncmapfile",
            index=models.Index(fields=["cnc_map"], name="kirovy_cncm_cnc_map_a1e8af_idx"),
        ),
        migrations.AddIndex(
            model_name="cncmapimagefile",
            index=models.Index(fields=["cnc_map"], name="kirovy_cncm_cnc_map_078511_idx"),
        ),
    ]
