# Generated by Django 4.2.23 on 2025-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0016_cncmapfile_cnc_user_cncmapimagefile_cnc_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cncmapimagefile",
            index=models.Index(fields=["is_extracted"], name="kirovy_cncm_is_extr_0259c5_idx"),
        ),
        migrations.AddIndex(
            model_name="cncmapimagefile",
            index=models.Index(fields=["cnc_user_id"], name="kirovy_cncm_cnc_use_b93113_idx"),
        ),
        migrations.AddIndex(
            model_name="cncmapimagefile",
            index=models.Index(fields=["cnc_game_id"], name="kirovy_cncm_cnc_gam_241448_idx"),
        ),
    ]
