# Generated by Django 4.2.23 on 2025-10-04 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0017_cncmapimagefile_kirovy_cncm_is_extr_0259c5_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmap",
            name="ban_count",
            field=models.IntegerField(default=0, help_text="How many times this user has been banned."),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="ban_date",
            field=models.DateTimeField(default=None, help_text="If banned, when the object was banned.", null=True),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="ban_expires",
            field=models.DateField(default=None, help_text="If banned, when the ban expires, if temporary.", null=True),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="ban_reason",
            field=models.CharField(default=None, help_text="If banned, the reason the object was banned.", null=True),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="moderated_by",
            field=models.ForeignKey(
                help_text="The most recent moderator who most recently modified this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_%(class)ss_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncmap",
            name="moderator_notes",
            field=models.TextField(help_text="Notes on moderator actions.", null=True),
        ),
        migrations.AddField(
            model_name="cncuser",
            name="moderated_by",
            field=models.ForeignKey(
                help_text="The most recent moderator who most recently modified this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_%(class)ss_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cncuser",
            name="moderator_notes",
            field=models.TextField(help_text="Notes on moderator actions.", null=True),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="is_banned",
            field=models.BooleanField(default=False, help_text="If true, object was banned for some reason."),
        ),
        migrations.AlterField(
            model_name="cncuser",
            name="ban_date",
            field=models.DateTimeField(default=None, help_text="If banned, when the object was banned.", null=True),
        ),
        migrations.AlterField(
            model_name="cncuser",
            name="ban_expires",
            field=models.DateField(default=None, help_text="If banned, when the ban expires, if temporary.", null=True),
        ),
        migrations.AlterField(
            model_name="cncuser",
            name="ban_reason",
            field=models.CharField(default=None, help_text="If banned, the reason the object was banned.", null=True),
        ),
        migrations.AlterField(
            model_name="cncuser",
            name="is_banned",
            field=models.BooleanField(default=False, help_text="If true, object was banned for some reason."),
        ),
    ]
