# Generated by Django 4.2.23 on 2025-10-22 16:03

from django.db import migrations, models
import kirovy.models.file_base


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0018_cncmap_ban_count_cncmap_ban_date_cncmap_ban_expires_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cncmapimagefile",
            name="file",
            field=models.ImageField(upload_to=kirovy.models.file_base.default_generate_upload_to),
        ),
    ]
