# Generated by Django 4.2.26 on 2025-11-23 00:19

from django.db import migrations, models
import kirovy.models.file_base


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0019_alter_cncmapimagefile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cncmapfile",
            name="file",
            field=models.FileField(max_length=2048, upload_to=kirovy.models.file_base.default_generate_upload_to),
        ),
        migrations.AlterField(
            model_name="cncmapimagefile",
            name="file",
            field=models.ImageField(max_length=2048, upload_to=kirovy.models.file_base.default_generate_upload_to),
        ),
        migrations.AlterField(
            model_name="mappreview",
            name="file",
            field=models.FileField(max_length=2048, upload_to=kirovy.models.file_base.default_generate_upload_to),
        ),
    ]
