# Generated by Django 4.2.23 on 2026-01-28 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0020_alter_cncmapfile_file_alter_cncmapimagefile_file_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cncmapfile",
            name="kirovy_cncm_cnc_map_a1e8af_idx",
        ),
        migrations.RemoveIndex(
            model_name="cncmapimagefile",
            name="kirovy_cncm_cnc_map_078511_idx",
        ),
        migrations.RemoveIndex(
            model_name="cncmapimagefile",
            name="kirovy_cncm_is_extr_0259c5_idx",
        ),
        migrations.RemoveIndex(
            model_name="cncmapimagefile",
            name="kirovy_cncm_cnc_use_b93113_idx",
        ),
        migrations.RemoveIndex(
            model_name="cncmapimagefile",
            name="kirovy_cncm_cnc_gam_241448_idx",
        ),
        migrations.AddField(
            model_name="cncmapfile",
            name="ip_address",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cncmapimagefile",
            name="ip_address",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mappreview",
            name="ip_address",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cncfileextension",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cncgame",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="is_legacy",
            field=models.BooleanField(
                db_index=True, default=False, help_text="If true, this is an upload from the old cncnet database."
            ),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="is_mapdb1_compatible",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=False, help_text="If true, this map will show up in normal searches and feeds."
            ),
        ),
        migrations.AlterField(
            model_name="cncmap",
            name="is_temporary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this will be deleted eventually. This flag is to support sharing in multiplayer lobbies.",
            ),
        ),
        migrations.AlterField(
            model_name="cncmapfile",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cncmapimagefile",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cncmapimagefile",
            name="is_extracted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="mapcategory",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="mappreview",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
