# Generated by Django 4.2.30 on 2026-10-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kirovy", "0021_remove_cncmapfile_kirovy_cncm_cnc_map_a1e8af_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cncmap",
            name="download_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Total number of times any file for this map has been downloaded. Used for 'popular' sorting.",
            ),
        ),
        migrations.CreateModel(
            name="CncMapDownloadStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField()),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "cnc_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="download_stats", to="kirovy.cncmap"
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cncmapdownloadstat",
            constraint=models.UniqueConstraint(fields=("cnc_map", "date"), name="unique_map_download_date"),
        ),
    ]
