name: CI
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run PyTest
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make CI env file
      run: cp ci.env .env

    - name: Build docker images
      run: docker compose build

    - name: Run containers
      run: docker compose up -d

    - name: Run PyTest
      run: docker exec -it mapdb-django-dev pytest
